# -- General Info --------------------------------------------------------------
type        : production 

# -- Services ------------------------------------------------------------------
production:   
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        skip_version_check: true
        safe: true
